apiVersion: v1
kind: ServiceAccount
metadata:
  name: urlshortener
  namespace: urlshortener
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: urlshortener-read-config
  namespace: urlshortener
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: urlshortener-read-config
  namespace: urlshortener
subjects:
  - kind: ServiceAccount
    name: urlshortener
    namespace: urlshortener
roleRef:
  kind: Role
  name: urlshortener-read-config
  apiGroup: rbac.authorization.k8s.io
