apiVersion: v1
kind: Service
metadata:
  name: {{ include "urlshortener.name" . }}
spec:
  selector:
    {{- include "urlshortener.labels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: ClusterIP
